import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
}

kotlin {
    jvmToolchain(21)

    compilerOptions {
        freeCompilerArgs.add("-Xannotation-default-target=param-property")
    }
}

// AGP doesn't expose `local.properties` as Gradle project properties in
// 9.x, so we load it explicitly with the standard `java.util.Properties`
// API. `local.properties` is auto-generated by Android Studio (with
// `sdk.dir`) and is gitignored, so it's the conventional home for
// credentials that must never enter version control.
val keystorePropertiesFile = rootProject.file("local.properties")
val keystoreProperties = Properties().apply {
    keystorePropertiesFile.inputStream().use { load(it) }
}
val keystorePath = keystoreProperties.getProperty("storeFile")?.let(::file)

android {
    namespace = "org.vestifeed"

    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = "org.vestifeed"
        minSdk = 34
        targetSdk = 37
        versionCode = 24
        versionName = "0.4.3"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        create("release") {
            storeFile = keystorePath
            storePassword = keystoreProperties.getProperty("storePassword")
            keyAlias = keystoreProperties.getProperty("keyAlias")
            keyPassword = keystoreProperties.getProperty("keyPassword")
                ?: keystoreProperties.getProperty("storePassword")
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
        }

        release {
            signingConfig = signingConfigs.getByName("release")

            isMinifyEnabled = true
            isShrinkResources = true

            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt")
            )
        }

        create("nightly") {
            initWith(getByName("release"))
            applicationIdSuffix = ".nightly"
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    testOptions {
        unitTests {
            isReturnDefaultValues = true
        }
    }

    lint {
        disable += "GradleDependency"
    }
}

dependencies {
    // Coroutines
    implementation(libs.kotlinx.coroutines)
    testImplementation(libs.kotlinx.coroutines.test)

    // AndroidX
    implementation(libs.androidx.fragment)
    implementation(libs.androidx.sqlite)
    implementation(libs.androidx.sqlite.framework)
    testImplementation(libs.androidx.sqlite.bundled.jvm)
    debugImplementation(libs.androidx.fragment.testing.manifest)
    androidTestImplementation(libs.androidx.fragment.testing)
    implementation(libs.androidx.work)
    androidTestImplementation(libs.androidx.work.testing)
    implementation(libs.androidx.browser)
    implementation(libs.androidx.lifecycle.runtime)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.swiperefreshlayout)
    implementation(libs.androidx.viewpager2)

    // Networking
    implementation(platform(libs.okhttp.bom))
    implementation(libs.okhttp)
    implementation(libs.okhttp.logging)
    testImplementation(libs.okhttp.mockwebserver)

    // JSON
    implementation(libs.gson)

    // UI
    implementation(libs.material)
    implementation(libs.coil)
    implementation(libs.coil.network)

    // Parsing
    implementation(libs.jsoup)
    implementation(libs.re2j)

    // Unit tests
    testImplementation(libs.junit)

    // Instrumented tests
    androidTestImplementation(libs.junit)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.espresso.core)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.ext.junit)
}
