name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Assemble APK
      run: ./gradlew assembleSelfSignedRelease
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "preview"
        prerelease: true
        title: "preview"
        files: "app/build/outputs/apk/selfSignedRelease/news-*.apk"
